Topic: NumPy for Data Science

Student Name: Devesh Panwar

Candidate ID: SIC202500060

---

### Problem 1: Find the memory size of any array.



In [24]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(f"{arr}")
print(f"Number of elements in the array (size): {arr.size}")
print(f"Size of one element in bytes (itemsize): {arr.itemsize}")
print(f"Total bytes consumed by the array data (nbytes): {arr.nbytes}")

[[1 2 3]
 [4 5 6]]
Number of elements in the array (size): 6
Size of one element in bytes (itemsize): 8
Total bytes consumed by the array data (nbytes): 48


### Problem 2: Create a null vector of size 10 but with the fifth value as 1.

In [25]:
import numpy as np
null_vector = np.zeros(10)
null_vector[4] = 1

print(f"Null vector with fifth value as 1: {null_vector}")

Null vector with fifth value as 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Problem 3: Reverse a vector (first element becomes last) using slicing.

In [26]:
import numpy as np
original_vector = np.array([1, 2, 3, 4, 5])
reversed_vector = original_vector[::-1]

print(f"Original vector: {original_vector}")
print(f"Reversed vector: {reversed_vector}")

Original vector: [1 2 3 4 5]
Reversed vector: [5 4 3 2 1]


### Problem 4: Create a 3x3 matrix with values ranging from 0 to 8 using `reshape()` and `arange()`.

In [27]:
import numpy as np
values = np.arange(9)
matrix = values.reshape(3, 3)

print(f"3x3 matrix with values 0 to 8:\n{matrix}")

3x3 matrix with values 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Problem 5: Find indices of non-zero elements from `[1,2,0,0,4,0]` using `nonzero()`.

In [28]:
import numpy as np
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)

print(f"Original array: {arr}")
print(f"Indices of non-zero elements: {non_zero_indices}")

Original array: [1 2 0 0 4 0]
Indices of non-zero elements: (array([0, 1, 4]),)


### Problem 6: Create a 3x3x3 array with random values.

In [29]:
import numpy as np
random_3d_array = np.random.rand(3, 3, 3)

print(f"3x3x3 array with random values:\n{random_3d_array}")

3x3x3 array with random values:
[[[0.69564726 0.05179291 0.57381241]
  [0.09156354 0.35414296 0.94612701]
  [0.40500475 0.54557322 0.85889804]]

 [[0.00897939 0.31969055 0.41240418]
  [0.31731532 0.30882367 0.91495419]
  [0.79787799 0.3271746  0.62883666]]

 [[0.20576551 0.0628816  0.99052751]
  [0.74533573 0.0159619  0.30862883]
  [0.76614261 0.37623907 0.69243669]]]


### Problem 7: Create a 10x10 array with random values and find the minimum and maximum values.

In [32]:
import numpy as np
random_10x10_array = np.random.rand(10, 10)
min_value = random_10x10_array.min()
max_value = random_10x10_array.max()

print(f"10x10 array with random values:\n{random_10x10_array}")
print(f"Minimum value in the array: {min_value}")
print(f"Maximum value in the array: {max_value}")

10x10 array with random values:
[[0.15983656 0.47780506 0.85426975 0.17028884 0.74124604 0.66000415
  0.1939215  0.46852316 0.49789228 0.84167165]
 [0.78967235 0.07766298 0.65718034 0.58025337 0.26906264 0.96008983
  0.63202468 0.23143999 0.65260833 0.51199185]
 [0.32643538 0.18002655 0.52759198 0.09108583 0.21747656 0.7238376
  0.34573653 0.90204344 0.42195262 0.37396477]
 [0.64220733 0.58841421 0.27830338 0.48560185 0.29271341 0.00197052
  0.25233196 0.21321994 0.31475891 0.93769997]
 [0.593245   0.15781163 0.73439063 0.60119457 0.6255925  0.66175983
  0.46308122 0.19390851 0.06317032 0.81642029]
 [0.44959863 0.55955817 0.05045656 0.20192479 0.71679897 0.15887958
  0.31563492 0.77729278 0.49685771 0.26341297]
 [0.75259214 0.44267264 0.48638371 0.40913108 0.70720819 0.51622125
  0.079862   0.72499016 0.07727684 0.16370161]
 [0.95336353 0.10477577 0.07625623 0.49559732 0.17212435 0.08260952
  0.56944669 0.54961256 0.47437595 0.86579512]
 [0.76352033 0.54725494 0.39242828 0.95314792 0.8

### Problem 8: Create a 2D array with 1 on the border and 0 inside.

In [33]:
import numpy as np
n_rows, n_cols = 5, 5
border_array = np.ones((n_rows, n_cols))
if n_rows > 2 and n_cols > 2:
    border_array[1:-1, 1:-1] = 0

print(f"2D array with 1 on border and 0 inside:\n{border_array}")

2D array with 1 on border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Problem 9: How to add a border (filled with 0s) around an existing array using `np.pad()`.

In [34]:
import numpy as np
existing_array = np.array([[1, 2], [3, 4]])
bordered_array_pad = np.pad(existing_array, pad_width=1, mode='constant', constant_values=0)

print(f"Original array:\n{existing_array}")
print(f"Array with 0-border using np.pad():\n{bordered_array_pad}")

Original array:
[[1 2]
 [3 4]]
Array with 0-border using np.pad():
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


### Problem 10: How to add a border (filled with 0s) around an existing array using fancy indexing.

In [37]:
import numpy as np
existing_array = np.array([[1, 2], [3, 4]])

row_padding = 1
col_padding = 1
new_rows = existing_array.shape[0] + 2 * row_padding
new_cols = existing_array.shape[1] + 2 * col_padding
bordered_array_manual = np.zeros((new_rows, new_cols), dtype=existing_array.dtype)

rows_to_fill = np.arange(row_padding, new_rows - row_padding)
cols_to_fill = np.arange(col_padding, new_cols - col_padding)
bordered_array_manual[np.ix_(rows_to_fill, cols_to_fill)] = existing_array

print(f"Original array:\n{existing_array}")
print(f"Array with 0-border (using fancy indexing):\n{bordered_array_manual}")

Original array:
[[1 2]
 [3 4]]
Array with 0-border (using fancy indexing):
[[0 0 0 0]
 [0 1 2 0]
 [0 3 4 0]
 [0 0 0 0]]


### Problem 11: Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [38]:
import numpy as np
values_below_diag = np.array([1, 2, 3, 4])
matrix_5x5 = np.diag(values_below_diag, k=-1)

print(f"5x5 matrix with values 1,2,3,4 just below the diagonal:\n{matrix_5x5}")

5x5 matrix with values 1,2,3,4 just below the diagonal:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
